### ISSUE TITLE
Autocomplete displays duplicated names for arguments

### ISSUE THREAD

**Issue by arsham** [disposablue/margo#5]
With [this](https://github.com/disposablue/margo/commit/ad990c68018299f72251a9bc0be830c8f0d9426a) commit, when you invoke the auto complete, it prints duplicate names for the arguments.

I think [this](https://github.com/disposablue/margo/blob/5335587d01015842c3eab7a8f9602f18609767b8/golang/gocode.go#L118) line should be reverted back to:
```go
fmt.Fprintf(buf, "${%d:%s}", i+1, name)
```

Margo version: **r18.03.23-1**

Thanks.

**Comment by DisposaBoy** [comment]
@arsham thanks for spotting this,  I will release a fix tomorrow.
